# 系統設定
baseURL = 'https://webberwu7.github.io/WebberWuBlog'
languageCode = 'zh-tw'
publishDir = 'docs'
theme = "m10c"

# 部落格設定
title = 'webber 筆記本'
paginate = 10
[params]
    author = 'webber'
    avatar = "images/avatar.jpg"
    description = '目前是一名後端工程師'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/webberwu7"